Updated BE deployment script, with new ec2 instance details.

diff --git a/.github/workflows/deployBackend.yml b/.github/workflows/deployBackend.yml
--- a/.github/workflows/deployBackend.yml
+++ b/.github/workflows/deployBackend.yml
@@ -5,24 +5,10 @@ on:
   push:
     branches:
       - main
+    paths:
+      - backend/**
 
 jobs:
-
-  retrieve-key:
-    runs-on: ubuntu-latest    
-    steps:
-    - name: Check out repository
-      uses: actions/checkout@v2
-
-    - name: Save private key to file
-      run: echo "${{ secrets.EC2_SSH_KEY }}" > private-key.pem
-      shell: bash
-
-    - name: Upload private key artifact
-      uses: actions/upload-artifact@v2
-      with:
-        name: private-key
-        path: private-key.pem
         
   deploy-backend:
     runs-on: ubuntu-latest
@@ -54,9 +40,9 @@ jobs:
     - name: Upload package to EC2
       run: |
         echo "Uploading package to EC2"
-        scp -o StrictHostKeyChecking=no backend.zip ec2-user@ec2-65-0-134-114.ap-south-1.compute.amazonaws.com:/home/ec2-user/ || { echo "SCP failed"; exit 1; }
+        scp -o StrictHostKeyChecking=no backend.zip ec2-user@ec2-3-110-32-123.ap-south-1.compute.amazonaws.com:/home/ec2-user/ || { echo "SCP failed"; exit 1; }
 
     - name: Deploy and run backend
       run: |
         echo "Restarting Services"
-        cat cloud/ec2RestartScript.sh | ssh ec2-user@ec2-65-0-134-114.ap-south-1.compute.amazonaws.com || { echo "SSH command failed"; exit 1; }
+        cat cloud/ec2RestartScript.sh | ssh ec2-user@ec2-3-110-32-123.ap-south-1.compute.amazonaws.com || { echo "SSH command failed"; exit 1; }
